package com.mlocek.shoppinglistmaker.ingredients;

public enum IngredientsEnum {
    CHICKEN_FILLET("Filet z kurczaka", IngredientGroupsEnum.MEAT),
    TURKEY_FILLET("Filet z indyka", IngredientGroupsEnum.MEAT),
    EGG("Jajko", IngredientGroupsEnum.DAIRY_PRODUCTS),
    HAM("Szynka kanapkowa", IngredientGroupsEnum.MEAT),
    VEGETABLES_MIX("Mieszanka warzyw na patelnie", IngredientGroupsEnum.FROZEN_PRODUCTS),
    VEGETABLES_MEXICAN_MIX("Mieszanka warzyw meksykańskich", IngredientGroupsEnum.FROZEN_PRODUCTS),
    VEGETABLES_ITALIAN_MIX("Mieszanka warzyw włoska", IngredientGroupsEnum.FROZEN_PRODUCTS),
    VEGETABLES_CALAFIOR_BROCC_MIX("Mieszanka warzyw z kalafiorem i brokułem", IngredientGroupsEnum.FROZEN_PRODUCTS),
    NATURAL_YOGURT_2("Jogurt naturalny 2%", IngredientGroupsEnum.DAIRY_PRODUCTS),
    NATURAL_YOGURT_0("Jogurt naturalny 0%", IngredientGroupsEnum.DAIRY_PRODUCTS),
    MILK_2("Mleko 2%", IngredientGroupsEnum.DAIRY_PRODUCTS),
    MOZARELLA_CHEESE("Mozzarella", IngredientGroupsEnum.DAIRY_PRODUCTS),
    PARMESAN_CHEESE("Parmezan", IngredientGroupsEnum.DAIRY_PRODUCTS),
    COTTAGE_CHEESE_THIN("Twaróg chudy", IngredientGroupsEnum.DAIRY_PRODUCTS),
    FETA_CHEESE("Feta", IngredientGroupsEnum.DAIRY_PRODUCTS),
    SOFT_GOAT_CHEESE("Ser kozi miękki", IngredientGroupsEnum.DAIRY_PRODUCTS),
    COTTAGE_CHEESE_GRAINY("Twaróg ziarnisty (serek wiejski)", IngredientGroupsEnum.DAIRY_PRODUCTS),
    INSTANT_COFFE("Kawa rozpuszczalna", IngredientGroupsEnum.OTHER),
    VINEGAR_BALSAMIC("Ocet balsamiczny", IngredientGroupsEnum.FAT_PRODUCTS),
    ORANGE_JUICE("Sok pomarańczowy", IngredientGroupsEnum.DRINKS),
    WATER("Woda", IngredientGroupsEnum.DRINKS),
    PUMPKIN_SEEDS("Pestki dyni", IngredientGroupsEnum.SEEDS_AND_NUTS),
    LUCER_GROUNDS("Kiełki lucerny", IngredientGroupsEnum.SEEDS_AND_NUTS),
    LEN_SEEDS("Len nasiona", IngredientGroupsEnum.SEEDS_AND_NUTS),
    BLUE_POPPY("Niebieski mak", IngredientGroupsEnum.SEEDS_AND_NUTS),
    ALMONDS("Migdały", IngredientGroupsEnum.SEEDS_AND_NUTS),
    HAZELNUTS("Orzechy laskowe", IngredientGroupsEnum.SEEDS_AND_NUTS),
    ITALIAN_NUTS("Orzechy włoskie", IngredientGroupsEnum.SEEDS_AND_NUTS),
    SESAME_SEEDS("Sezam nasiona", IngredientGroupsEnum.SEEDS_AND_NUTS),
    SUNFLOWER_SEEDS("Słonecznik nasiona", IngredientGroupsEnum.SEEDS_AND_NUTS),
    RED_LENTIL("Czerwona soczewica", IngredientGroupsEnum.SEEDS_AND_NUTS),
    PINEAPPLE_JUICE("Sok ananasowy", IngredientGroupsEnum.DRINKS),
    PINEAPPLE("Ananas", IngredientGroupsEnum.FRUITS),
    BANANA("Banan", IngredientGroupsEnum.FRUITS),
    LEMON("Cytryna", IngredientGroupsEnum.FRUITS),
    GRAPEFRUIT("Grejfrut", IngredientGroupsEnum.FRUITS),
    PEAR("Gruszka", IngredientGroupsEnum.FRUITS),
    APPLE("Jabłko", IngredientGroupsEnum.FRUITS),
    KIWI("Kiwi", IngredientGroupsEnum.FRUITS),
    MANGO("Mango", IngredientGroupsEnum.FRUITS),
    ORANGE("Pomarańcza", IngredientGroupsEnum.FRUITS),
    STRAWBERRIES("Truskawki", IngredientGroupsEnum.FRUITS),
    CHERRIES("Wiśnie", IngredientGroupsEnum.FRUITS),
    GRAHAM_BREAD("Chleb graham", IngredientGroupsEnum.BREAD),
    HORSERADISH("Chrzan", IngredientGroupsEnum.PRESERVES),
    CANNED_CORN("Kukurydza konserwowa", IngredientGroupsEnum.PRESERVES),
    PEANUT_BUTTER("Masło orzechowe", IngredientGroupsEnum.PRESERVES),
    DRIED_TOMATOES("Suszone pomidory", IngredientGroupsEnum.PRESERVES),
    DRIED_CRANBERRY("Żurawina suszona", IngredientGroupsEnum.PRESERVES),
    BASIL("Bazylia", IngredientGroupsEnum.SPICES),
    BASIL_LEAVES("Bazylia liście", IngredientGroupsEnum.VEGETABLES),
    CHILI("Chili", IngredientGroupsEnum.SPICES),
    CURRY("Curry", IngredientGroupsEnum.SPICES),
    DRIED_GINGER("Imbir suszony", IngredientGroupsEnum.SPICES),
    DILL("Koperek", IngredientGroupsEnum.VEGETABLES),
    PROVENCE_HERBS("Zioła prowansalskie", IngredientGroupsEnum.SPICES),
    SALOMON_FILLET("Łosoś filet", IngredientGroupsEnum.FISH),
    SALMON("Łosoś", IngredientGroupsEnum.FISH),
    RED_BEAN("Fasola czerwona", IngredientGroupsEnum.PRESERVES),
    COCOA("Kakao", IngredientGroupsEnum.OTHER),
    HONEY("Miód", IngredientGroupsEnum.SWEETS),
    AVOCADO("Awokado", IngredientGroupsEnum.FAT_PRODUCTS),
    BUTTER("Masło", IngredientGroupsEnum.FAT_PRODUCTS),
    RAPESEED_OIL("Olej rzepakowy", IngredientGroupsEnum.FAT_PRODUCTS),
    OLIVE_OIL("Oliwa z oliwek", IngredientGroupsEnum.FAT_PRODUCTS),
    SWEET_POTATO("Batat", IngredientGroupsEnum.VEGETABLES),
    CHARD("Boćwina", IngredientGroupsEnum.VEGETABLES),
    BROCCOLI("Brokuł", IngredientGroupsEnum.VEGETABLES),
    ONION("Cebula", IngredientGroupsEnum.VEGETABLES),
    COURGETTE("Cukinia", IngredientGroupsEnum.VEGETABLES),
    GARLIC("Czosnek", IngredientGroupsEnum.VEGETABLES),
    KALE("Jarmuż", IngredientGroupsEnum.VEGETABLES),
    CARROT("Marchew", IngredientGroupsEnum.VEGETABLES),
    RED_PAPRICA("Czerwona papryka", IngredientGroupsEnum.VEGETABLES),
    GREEN_PAPRICA("Zielona papryka", IngredientGroupsEnum.VEGETABLES),
    MUSHROOM("Pieczarka", IngredientGroupsEnum.VEGETABLES),
    PARSLEY_LEAVES("Pietruszka liście", IngredientGroupsEnum.VEGETABLES),
    TOMATO("Pomidor", IngredientGroupsEnum.VEGETABLES),
    CHERRY_TOMATOES("Pomidorki koktajlowe", IngredientGroupsEnum.VEGETABLES),
    RUKOLA("Rukola", IngredientGroupsEnum.VEGETABLES),
    PORE("Por", IngredientGroupsEnum.VEGETABLES),
    LETTUCE("Sałata maślana", IngredientGroupsEnum.VEGETABLES),
    CELERY_ROOT("Seler korzeniowy", IngredientGroupsEnum.VEGETABLES),
    CELERY_LEAVES("Seler naciowy", IngredientGroupsEnum.VEGETABLES),
    CHIVE("Szczypiorek", IngredientGroupsEnum.VEGETABLES),
    SPINACH("Szpinak świeży", IngredientGroupsEnum.VEGETABLES),
    POTATOES("Ziemniaki", IngredientGroupsEnum.VEGETABLES),
    MILLET("Kasza jaglana", IngredientGroupsEnum.CEREAL_PRODUCTS),
    PEARL_BARLEY("Kasza jęczmienna perłowa", IngredientGroupsEnum.CEREAL_PRODUCTS),
    BARLEY("Kasza jęczmienna", IngredientGroupsEnum.CEREAL_PRODUCTS),
    COUS_COUS("Kasza kuskus", IngredientGroupsEnum.CEREAL_PRODUCTS),
    WHOLE_GRAIN_PASTA("Makaron pełnoziarnisty", IngredientGroupsEnum.CEREAL_PRODUCTS),
    WHEAT_FLOUR_1850("Mąka pszenna typ 1850", IngredientGroupsEnum.CEREAL_PRODUCTS),
    OATMEAL("Płatki owsiane", IngredientGroupsEnum.CEREAL_PRODUCTS),
    BASMATI_RICE("Ryż basmati", IngredientGroupsEnum.CEREAL_PRODUCTS),
    BROWN_RICE("Ryż brązowy", IngredientGroupsEnum.CEREAL_PRODUCTS),
    GREEN_CUCUMBER("Ogórek zielony", IngredientGroupsEnum.VEGETABLES),
    SMOKED_MACKEREL("Wędzona makrela", IngredientGroupsEnum.FISH),
    LAMB_LETTUCE("Roszponka", IngredientGroupsEnum.VEGETABLES),
    PEACH("Brzoskwinia", IngredientGroupsEnum.FRUITS),
    CINNAMON("Cynamon", IngredientGroupsEnum.SPICES),
    GREEN_PEAS("Groszek zielony", IngredientGroupsEnum.PRESERVES),
    NUTMEG("Gałka muszkatałowa", IngredientGroupsEnum.SPICES),
    BUCKWHEAT("Kasza gryczana", IngredientGroupsEnum.CEREAL_PRODUCTS),
    RASPBERRIES("Maliny", IngredientGroupsEnum.FRUITS),
    NECTARINE("Nektarynka", IngredientGroupsEnum.FRUITS),
    CASHEW_NUT("Orzech nerkowca", IngredientGroupsEnum.SEEDS_AND_NUTS),
    THYME("Tymianek", IngredientGroupsEnum.SPICES),
    COCONUT_MILK("Mleczko kokosowe", IngredientGroupsEnum.PRESERVES),
    MILLET_FLAKES("Płatki jaglane", IngredientGroupsEnum.CEREAL_PRODUCTS),
    RAISINS("Rodzynki", IngredientGroupsEnum.SEEDS_AND_NUTS),
    RADISH("Rzodkiewka", IngredientGroupsEnum.VEGETABLES),
    TUNA("Tuńczyk w wodzie", IngredientGroupsEnum.FISH),
    BEETROOT("Burak", IngredientGroupsEnum.VEGETABLES),
    PICKLE("Ogórek kiszony", IngredientGroupsEnum.PRESERVES),
    OLIVES("Oliwki", IngredientGroupsEnum.PRESERVES),
    SMOKED_SALOM("Wędzony łosoś", IngredientGroupsEnum.FISH);

    private final String text;
    private final IngredientGroupsEnum group;


    IngredientsEnum(String ingredient, IngredientGroupsEnum group) {
        this.text = ingredient;
        this.group = group;
    }

    public String getText() {
        return text;
    }

    public String getGroup(){
        return group.getText();
    }
}
